# Generated by Django 4.1.1 on 2022-09-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employerprofile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name'),
        ),
    ]
