# Generated by Django 4.1.1 on 2022-09-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('EMPLOYER', 'Employer'), ('JOB_SEEKER', 'Job_Seeker')], max_length=50, null=True, verbose_name='Type'),
        ),
    ]
