# Generated by Django 4.1.1 on 2022-09-28 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcquestion',
            options={'ordering': ['topic'], 'verbose_name': 'Multiple Choice Question', 'verbose_name_plural': 'Multiple Choice Questions'},
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcquestions', to='assessment.assessment', verbose_name='Assessment'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.questiontopic', verbose_name='Topic'),
        ),
        migrations.CreateModel(
            name='TrueFalseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter you question', max_length=1000, verbose_name='Content')),
                ('is_true', models.BooleanField(default=False, help_text='Is This True?', verbose_name='Is True')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfquestions', to='assessment.assessment', verbose_name='Assessment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.questiontopic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'True False Question',
                'verbose_name_plural': 'True False Questions',
                'ordering': ['topic'],
            },
        ),
    ]
