# Generated by Django 4.1.1 on 2022-10-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_mcquestion_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='mcquestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='shortanswerquestion',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='truefalsequestion',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='MCQuestion',
        ),
        migrations.DeleteModel(
            name='ShortAnswerQuestion',
        ),
        migrations.DeleteModel(
            name='TrueFalseQuestion',
        ),
    ]
