# Generated by Django 4.1.1 on 2022-10-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_remove_choice_question_remove_mcquestion_assessment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('SHORT_ANSWER', 'Short Answer'), ('TRUE_FALSE', 'True False')], max_length=50, verbose_name='Type'),
        ),
    ]
