# Generated by Django 4.1.1 on 2022-11-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
