# Generated by Django 4.1.1 on 2022-12-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_alter_result_job_seeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='slug',
            field=models.SlugField(blank=True, max_length=6, null=True, verbose_name='Slug'),
        ),
    ]
