# Generated by Django 4.1.1 on 2022-12-17 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
