# Generated by Django 4.1.1 on 2022-09-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekersProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, max_length=255, null=True, verbose_name='Summary')),
                ('gender', models.IntegerField(blank=True, null=True, verbose_name='Gender')),
                ('date_of_birth', models.DateField(null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
            ],
        ),
    ]
