# Generated by Django 4.1.1 on 2022-10-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0005_remove_choice_question_remove_mcquestion_assessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter you question', max_length=1000, verbose_name='Content')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer_questions', to='assessment.assessment', verbose_name='Assessment')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.questiontopic', verbose_name='Topic')),
            ],
            options={
                'verbose_name': 'Short Answer Question',
                'verbose_name_plural': 'Short Answer Questions',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Write down the answer for the Short Answer Question', max_length=1000, verbose_name='Content')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shortanswer.shortanswerquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
