# Generated by Django 4.1.1 on 2022-10-05 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Job', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Job Description', max_length=1500, verbose_name='Description')),
                ('location', models.CharField(max_length=150, verbose_name='Job Location')),
                ('type', models.IntegerField(choices=[(1, 'Full Time'), (2, 'Part Time'), (3, 'Internship')], verbose_name='Job Type')),
                ('category', models.CharField(choices=[('WEB_DESIGN', 'Web Design'), ('WEB_DEVELOPMENT', 'Web Development'), ('FULL_STACK', 'Full Stack'), ('MOBILE_DEVELOPMENT', 'Mobile Development')], max_length=100, verbose_name='Job Category')),
                ('last_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('company_description', models.TextField(max_length=300, verbose_name='Company Description')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
    ]
