# Generated by Django 4.1.1 on 2022-10-06 16:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0002_initial'),
        ('employers', '0002_initial'),
        ('job', '0002_alter_job_create_by_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.ImageField(blank=True, null=True, upload_to='resumes/')),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobseekers.jobseekersprofile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employers.employerprofile')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_description',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job.job'),
        ),
    ]
